[app]
secret = "secret-k"

[api]
host = "0.0.0.0"
port = 3301
workerNum = 2

[db]
host = "rm-wz928xy0fle677v83.mysql.rds.aliyuncs.com"
port = 3306
username = "wxgame"
password = "MD9(ZWyl*0j98B7g"
database = "wxgame"
charset = "utf8mb4"
connectTimeout = 2000
